version: 2.1

commands:
  build-images:
    steps:
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Build images
          command: |
            export DOCKER_BUILDKIT=1
            ./.circleci/image_names.sh | xargs -I % docker build % -t cszatmary/%

jobs:
  build-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - build-images
  build-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Docker login
          command: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USER --password-stdin
      - build-images
      - run:
          name: Push images
          command: ./.circleci/image_names.sh | xargs -I % docker push cszatmary/%

workflows:
  build-test:
    jobs:
      - build-test:
          filters:
            branches:
              ignore: main
  build-push:
    jobs:
      - build-push:
          context: cszatmary-global
          filters:
            branches:
              only: main
